#!/usr/bin/env bash
# my process
# my process

command="$1"

    "start")
        if [ -f /var/run/my_process.pid ]; then
            echo "manage_my_process is already running."
        else
            (while true; do
                echo "I am alive!" >> /tmp/my_process
                sleep 2
            done) &
            echo $! > /var/run/my_process.pid
            echo "manage_my_process started"
        fi
        ;;
    "stop")
        if [ -f /var/run/my_process.pid ]; then
            kill -9 $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running."
        fi
        ;;
    "restart")
        if [ -f /var/run/my_process.pid ]; then
            kill -9 $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
        fi
        (while true; do
            echo "I am alive!" >> /tmp/my_process
            sleep 2
        done) &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac

